name: "TestPlugin"
main: "com.bocbin.testplugin.Main"  # the location of the main class
version: "1.1.0 Alpha Centauri"
author: "Bocbin"
api-version: "1.13"

commands:
  Hello:  # ignore the error hopefully it works
  Launch:
    aliases: "lh"
  Doctor:
  GodBoots:
