name: "TestPlugin"
main: "com.bocbin.testplugin.Main"  # the location of the main class
version: "1.3.0 Capricorn"
author: "Bocbin"
api-version: "1.13"

commands:
  Hello:  # ignore the error hopefully it works
  Launch:
    aliases: "lh"
  Doctor:
  GodBoots:
  StarTrident:
  ChangeTeam:
    aliases: "changeteams"